device: cpu

model:
  name: GoogLeNet
  input_size: [3, 224, 224]
  output_dim: 10
  training: true

training:
  batch_size: 128
  num_workers: 0
  shuffle_train: true
  epochs: 20
  criterion: CrossEntropy
  update_freq: 10
  optimizer:
    type: SGD
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0002
